### ISSUE TITLE
ng serve cannot run the project 

### ISSUE THREAD

**Issue by qiuyunzhao** [NorthwoodsSoftware/gojs-angular-basic#1]
E:\AngularProject\gojs-angular-basic>ng serve
No projects support the 'serve' target.
Error: No projects support the 'serve' target.
    at ServeCommand.initialize (E:\AngularProject\gojs-angular-basic\node_modules\@angular\cli\models\architect-command.js:50:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by rjohnson465** [comment]
Thanks for bringing this to my attention. I have just updated the project to fix this issue.

Try it again now; it should work. Be sure to first install all dependencies with "npm install"
